--
-- PostgreSQL database dump
--

\restrict bdO3nvarcRWX0yzGpPHfmHmiYNyt1x2gWB3PIwswVfKSeSH5YWnaBt3P90NY05V

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-08-19 11:01:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16438)
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    id_member bigint NOT NULL,
    member_name character varying(255),
    member_surname character varying(255)
);


--
-- TOC entry 223 (class 1259 OID 16437)
-- Name: members_id_member_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.members ALTER COLUMN id_member ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_member_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16399)
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id_project bigint NOT NULL,
    name character varying(255),
    status character varying(255),
    ts_deadline bigint,
    id_assigned_team_member bigint,
    budget bigint,
    ts_creation bigint,
    details text
);


--
-- TOC entry 220 (class 1259 OID 16405)
-- Name: projects_id_project_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id_project ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.projects_id_project_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16408)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id_user bigint NOT NULL,
    username character varying(100),
    password character varying(100)
);


--
-- TOC entry 222 (class 1259 OID 16416)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5024 (class 0 OID 16438)
-- Dependencies: 224
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.members (id_member, member_name, member_surname) FROM stdin;
6	Rosa Marina	Achinquipa Salcedo
8	Franco	Falsaperla
7	Annah	Gabry
10	Carmen	Miranda
11	Jack	White
5	Eros	Cappello
\.


--
-- TOC entry 5019 (class 0 OID 16399)
-- Dependencies: 219
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.projects (id_project, name, status, ts_deadline, id_assigned_team_member, budget, ts_creation, details) FROM stdin;
6	Internal Project Management Platform for Teams and Departments	completed	1786831200	6	50	1786969581	Develop an internal project management platform that allows employees to create and manage projects, assign team members, define deadlines, track budgets, update project status, and store relevant project information. Managers should also have access to reporting features to monitor the overall performance of ongoing projects.
4	CRM Integration	on-hold	1787004000	5	45000	1786962712231	Integrate the existing CRM system with the internal platform to synchronize customers, contacts, and sales data.
7	Legacy Database Migration and Data Structure Modernization	active	1787090400	5	20000	1787035952	Migrate the existing legacy database to a new database infrastructure while preserving all historical information. The project includes analyzing the current data structure, cleaning inconsistent records, transforming outdated fields, validating migrated data, and ensuring that the application continues to work correctly after the migration.
5	Business Intelligence Reporting and Data Visualization Platform	active	1790719200	7	6000	1786962754	Develop a reporting platform that allows managers to generate customized reports from business data. Users should be able to filter information by date, department, project, customer, and other relevant parameters, while also being able to visualize important metrics using charts and export reports for further analysis.
14	Marketing Campaign	active	1787608800	6	5000	1787068503	Plan and launch a digital marketing campaign focused on increasing website traffic and generating new leads.
15	Coffee Before Production	active	1787608800	10	140	1787068622	Improve the development and deployment workflow by introducing automated testing, continuous integration, deployment pipelines, and better monitoring. The system should reduce manual deployment steps and make releases safer and more predictable.
16	Mission: No More Excel	on-hold	1787090400	7	300	1787068666	Replace a collection of manually maintained spreadsheets with a centralized web application for managing projects, budgets, deadlines, team members, and reports. The system should reduce duplicated information and eliminate common spreadsheet errors.
13	Mobile App Development	on-hold	1785880800	10	15000	1787065357	Develop a mobile application for customers to manage their accounts, view services, and receive notifications.
8	Website Redesign	active	1785535200	5	1000	1787036923	Redesign the company website with a modern layout, improved navigation, and better mobile responsiveness.
\.


--
-- TOC entry 5021 (class 0 OID 16408)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id_user, username, password) FROM stdin;
1	admin	$2b$10$4rzXjOTbgT2OToZ4Oox85uSWnp1ihQey0TX4NvrLOLNtBjiona4P.
\.


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 223
-- Name: members_id_member_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.members_id_member_seq', 11, true);


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 220
-- Name: projects_id_project_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.projects_id_project_seq', 16, true);


--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 222
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_user_seq', 1, true);


--
-- TOC entry 4871 (class 2606 OID 16443)
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id_member);


--
-- TOC entry 4867 (class 2606 OID 16404)
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id_project);


--
-- TOC entry 4869 (class 2606 OID 16415)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


-- Completed on 2026-08-19 11:01:51

--
-- PostgreSQL database dump complete
--

\unrestrict bdO3nvarcRWX0yzGpPHfmHmiYNyt1x2gWB3PIwswVfKSeSH5YWnaBt3P90NY05V

